name: LeetCrafting
version: "${version}"
main: com.leet.crafting.LeetCrafting
api-version: "26.2"
description: Leet crafting plugin - custom items and recipes
author: Leet
softdepend: [Vault, LeetCore]
